--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/my_yard/.vr_settings.yaml"
width: 1312
height: 669
panel_pos: 267
notebook_panel_position: 400
run_command_line: ruby my_yard
open_files:
- "/home/eric/vrp/my_yard/my_yard"
- "/home/eric/vrp/my_yard/src/YardThemeDefaults.rb"
- "/home/eric/vrp/my_yard/src/MyYard.rb"
- "/home/eric/vrp/my_yard/src/YardTheme.rb"
- "/home/eric/vrp/my_yard/README.md"
open_folders:
- "/home/eric/vrp/my_yard"
- "/home/eric/vrp/my_yard/src"
current_file: "/home/eric/vrp/my_yard/README.md"
current_line: 25
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
