--- !ruby/object:VR_ENV
vr_yaml_file: ".vr_settings.yaml"
width: 1466
height: 815
panel_pos: 360
notebook_panel_position: 452
run_command_line: ruby my_yard
open_files:
- "/home/eric/vrp/my_yard/my_yard"
- "/home/eric/vrp/my_yard/src/MyYard.rb"
open_folders:
- "/home/eric/vrp/my_yard"
- "/home/eric/vrp/my_yard/projects"
current_file: "/home/eric/vrp/my_yard/src/MyYard.rb"
current_line: 58
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
browser: firefox
backup_path: "/home/eric"
tab_spaces: 2
glade_path: glade-3
font_name: Monospace 10
