--- !ruby/object:VR_ENV
vr_yaml_file: "/home/eric/vrp/my_yard/.vr_settings.yaml"
width: 1208
height: 600
panel_pos: 360
notebook_panel_position: 400
run_command_line: ruby my_yard
open_files:
- "/home/eric/vrp/my_yard/my_yard"
- "/home/eric/vrp/my_yard/src/MyYard.rb"
open_folders:
- "/home/eric/vrp/my_yard"
current_file: "/home/eric/vrp/my_yard/my_yard"
current_line: 11
rdoc_command_line: rdoc -x README
builder: !ruby/object:Gtk::Builder {}
top_level_window: false
