#!/usr/bin/ruby

require "vrlib"
require Dir.home + '/vrp/yard/lib/yard'

# from require_all gem:
require_rel 'src/'

$theme_root = File.join(Dir.home, "my_yard", "themes")
$template_root = File.expand_path(File.join(File.dirname(__FILE__), "templates"))
$project_root = File.join(Dir.home, "my_yard", "projects")

$default_theme = YardTheme.new()

VR::save_yaml(YardTheme.new(), File.join($theme_root, "default.yaml"))

$open_project = (ARGV[0] and File.directory?(ARGV[0])) ? File.expand_path(ARGV[0]) : Dir.pwd

$env = VR::load_yaml(GlobalSettings, File.join(Dir.home, "my_yard", "global_settings.yaml"))

loop do 
  $env.add_project($open_project) 
  proj = VR::load_yaml(MyYard, File.join($open_project, "my_yard.yaml"))
  proj.show_glade()
  break if $open_project == :exit
end


